[[keyboard.bindings]]
key = "Comma"
mods = "Command"
command = { program = "sh", args = ["-c","open ~/.config/alacritty/alacritty.yml"]}

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Space"
mods = "Alt"
chars = " "

[[keyboard.bindings]]
key = "Back"
mods = "Super"
chars = "\\x15" # delete word/line

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\\x1bb" # one word left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\\x1bf" # one word right

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\\x1bOH"
mode = "AppCursor" # Home

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\\x1bOF"
mode = "AppCursor"

[font]
size = 6.0

# TokyoNight Alacritty Colors
[colors]
# Default colors
primary = { background = '0x1a1b26', foreground = '0xc0caf5' }

# Normal colors
[colors.normal]
black =   '0x15161e'
red =     '0xf7768e'
green =   '0x9ece6a'
yellow =  '0xe0af68'
blue =    '0x7aa2f7'
magenta = '0xbb9af7'
cyan =    '0x7dcfff'
white =   '0xa9b1d6'

# Bright colors
[colors.bright]
black =   '0x414868'
red =     '0xf7768e'
green =   '0x9ece6a'
yellow =  '0xe0af68'
blue =    '0x7aa2f7'
magenta = '0xbb9af7'
cyan =    '0x7dcfff'
white =   '0xc0caf5'

[[colors.indexed_colors]]
index = 16
color = '0xff9e64'

[[colors.indexed_colors]]
index = 17
color = '0xdb4b4b'

[cursor.style]
shape = "Beam"
blinking = "Always"
